import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blogsite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-zinc-900 px-2">

        <header className="border-b border-zinc-800 py-12">
          <nav className="mx-auto flex max-w-4xl items-center justify-between">
            <Link href="/" className="font-semibold tracking-tight">
              Home
            </Link>

            <div className="flex gap-6 text-sm text-zinc-400">
              <Link href="/writing" className="hover:text-white">Writing</Link>
              <Link href="/projects" className="hover:text-white">Projects</Link>
              <Link href="/about" className="hove:text-white">About</Link>
            </div>

          </nav>
        </header>


        {children}

        <footer className="border-t border-zinc-800">
          <div className="mx-auto max-w-5xl px-6 py-8 text-sm text-zinc-500">
            © {new Date().getFullYear()} Steve Chester
          </div>
        </footer>
      </body>
    </html >
  );
}
